Repository YusukeHosonuma/SwiftPrettyPrint, pull requests merged in 2020-12, with the labels that each got.

#124 Support pretty-print for errors in failures and refactor UnitTest on Combine
  Example/SwiftPrettyPrintExample/Source/ContentViewModel.swift
  Example/SwiftPrettyPrintExample/Source/Dog.swift
  Sources/Public/CombineExtension.swift
  Tests/SwiftPrettyPrintTests/Public/CombineExtensionTests.swift
Labels: feature: formatter, refactor

#130 add prettyPrint Command for LLDB with regex
  .lldbinit
  README.md
Labels: LLDB integration

#135 release: 1.1.0
  README.md
  version.txt
Labels: documentation
