Repository YusukeHosonuma/SwiftPrettyPrint, pull requests merged in 2022-05, with the labels that each got.

#177 Improve description of colored option in README.md
  Image/colored-option.png
  README.md
Labels: documentation

#179 Support: `@Published` property of SwiftUI
  Sources/Core/PrettyDescriber.swift
Labels: feature: type

#180 support: SwiftUI property wrappers
  Sources/Core/PrettyDescriber.swift
Labels: feature: type

#181 support: `@GestureState`
  Sources/Core/PrettyDescriber.swift
Labels: feature: type

#182 fix: occur infinity-loop when include `@FocusState`
  Sources/Core/PrettyDescriber.swift
Labels: bug

#185 support: `@FocucedBinding` of SwiftUI
  Sources/Core/PrettyDescriber.swift
Labels: feature: type

#186 support: `@FocusedValue` of SwiftUI
  Sources/Core/PrettyDescriber.swift
Labels: feature: type

#187 support: `@Namespace` of SwiftUI
  Sources/Core/PrettyDescriber.swift
Labels: feature: type

#188 support: `@ScaledMetric` of SwiftUI
  Sources/Core/PrettyDescriber.swift
Labels: feature: type

#190 temporary support: `@FetchRequest`
  Sources/Core/PrettyDescriber.swift
Labels: feature: type

#191 update: README
  README.md
Labels: documentation

#192 fix to make the string being attached to coloredLogStream colored again
  Sources/Public/Pretty.swift
Labels: bug
